### ISSUE TITLE
XCode Warning: 'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by 5fcgdaeb** [EFPrefix/EFAutoScrollLabel#3]
As of XCode 9.1, the following warning is issued:

'characters' is deprecated: Please use String or Substring directly -> EFTAutoScrollLabel.swift

XCode: 9.4
EFAutoScrollLabel: 4.0.2
Swift: 3.3

It would be great to take care of this to reduce the warnings in the build log. It is a very simple fix, I can submit a PR if you would like.

Thanks!

**Comment by EyreFree** [comment]
@5fcgdaeb 

Fixed in [5.1.0](https://github.com/EFPrefix/EFAutoScrollLabel/releases/tag/5.1.0).
