### ISSUE TITLE
Main Thread Checker: UI API called on a background thread:

### ISSUE THREAD

**Issue by freakdragon** [EFPrefix/EFAutoScrollLabel#6]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EFPrefix/EFAutoScrollLabel/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EFPrefix/EFAutoScrollLabel/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

### Issue Description
The error appears.
> Main Thread Checker: UI API called on a background thread: -[UILabel text]
> PID: 6718, TID: 54018, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 21

#### Description

It causes by this code.

```
    @objc public func scrollLabelIfNeeded() {
        if text == nil || text?.isEmpty == true {
            return
        }

        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            self.scrollLabelIfNeededAction()
        }
    }
```

#### Reproduce

I've got it by adding label to UIPickerView as custom view. If I do nothing for about 10 seconds the error appears.

#### Other Comment

This code fixed it.

```
    @objc public func scrollLabelIfNeeded() {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            if self.text == nil || self.text?.isEmpty == true {
                return
            }
            self.scrollLabelIfNeededAction()
        }
    }
```

**Comment by EyreFree** [comment]
@freakdragon

Fixed in [5.1.1](https://github.com/EFPrefix/EFAutoScrollLabel/releases/tag/5.1.1).
